### PR TITLE
[CRITICAL] Hello sudo intellectual abschill (Alex), I'm fixing your punctuation

### PR DESCRIPTION
**Pull request by SamG06**
"doesnt" needs an apostrophe to make my spell checker stop yelling

### CODE REVIEW

**Comment by Mafrans** [comment]
Does this change pass the test suite?

**Comment by abschill** [comment]
why is your spell checker running on source code files lol

**Comment by SamG06** [comment]
> why is your spell checker running on source code files lol

@abschill Nothing is safe. I'm glad to be a critical contributor to this project.

**Comment by abschill** [comment]
fix windows vfs bug

**Pull request merged**
